/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TipsRouteImport } from './routes/tips'
import { Route as SightingsRouteImport } from './routes/sightings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'

const TipsRoute = TipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => rootRouteImport,
} as any)
const SightingsRoute = SightingsRouteImport.update({
  id: '/sightings',
  path: '/sightings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/sightings': typeof SightingsRoute
  '/tips': typeof TipsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/sightings': typeof SightingsRoute
  '/tips': typeof TipsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/messages': typeof MessagesRoute
  '/notes': typeof NotesRoute
  '/sightings': typeof SightingsRoute
  '/tips': typeof TipsRoute
  '/profile/$userId': typeof ProfileUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/messages'
    | '/notes'
    | '/sightings'
    | '/tips'
    | '/profile/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/messages'
    | '/notes'
    | '/sightings'
    | '/tips'
    | '/profile/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/messages'
    | '/notes'
    | '/sightings'
    | '/tips'
    | '/profile/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MessagesRoute: typeof MessagesRoute
  NotesRoute: typeof NotesRoute
  SightingsRoute: typeof SightingsRoute
  TipsRoute: typeof TipsRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tips': {
      id: '/tips'
      path: '/tips'
      fullPath: '/tips'
      preLoaderRoute: typeof TipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sightings': {
      id: '/sightings'
      path: '/sightings'
      fullPath: '/sightings'
      preLoaderRoute: typeof SightingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MessagesRoute: MessagesRoute,
  NotesRoute: NotesRoute,
  SightingsRoute: SightingsRoute,
  TipsRoute: TipsRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
